### ISSUE TITLE
Issues 템플릿 관련 의견 

### ISSUE THREAD

**Issue by lat230627** [eGovFramework/egovframe-runtime#116]
Issues 템플릿 관련 의견 드립니다. 

Q/A 기이슈 템플릿이 추가됐으면 좋겠습니다. 

' Question
  Please ask and answer questions here. ' 
=> 표준프레임워크 Q/A 게시판 링크 

기능 요구 및 의견 Feature Request 템플릿이 
기능 요구 사항 외에 의견(비기능, 프로젝트 관리 개선 등)도 올릴 수 있는 템플릿이었으면 좋겠습니다.

**Comment by jei007** [comment]
컨트리뷰션 관련이나 그 이외의 궁금하신 점은
표준프레임워크 포털의 [묻고답하기 게시판](https://www.egovframe.go.kr/home/sub.do?menuNo=69)에
남겨주시면 감사하겠습니다.

표준프레임워크에 대한 관심에 감사드립니다.
