### ISSUE TITLE
README.md 오타

### ISSUE THREAD

**Issue by kangjung** [eGovFramework/egovframe-runtime#117]
### 연락처 Contact

aaggf1112@gmail.com

### 추가 요청 기능명 Feature Name

README.md 수정

### 기능 상세 설명 Feature Description

![image](https://github.com/eGovFramework/egovframe-runtime/assets/28768760/c767473c-59ca-451a-9051-550214f101cd)
![image](https://github.com/eGovFramework/egovframe-runtime/assets/28768760/fae95c4a-0ec1-4c64-a00e-51468800d210)

실행환경 구성 및 실행환경 구성 설명부분의 org.egovframe.rte.psl.data.dataaccess 가 실제 코드 경로에서는 org.egovframe.rte.psl.dataaccess 로 되어있습니다.
수정이 필요할것 같습니다.
![image](https://github.com/eGovFramework/egovframe-runtime/assets/28768760/684e5d49-0074-49a1-a5e6-7b2286bcc527)

**Comment by jei007** [comment]
표준프레임워크에 대한 지속적인 참여에
대단히 감사드립니다.
