### ISSUE TITLE
[기능요구(Feature)]: Contribution Guide를 readme에서 접근할 수 있으면 좋겠습니다.

### ISSUE THREAD

**Issue by hckhead** [eGovFramework/egovframe-runtime#120]
### 연락처 Contact

yoo.insung@gmail.com

### 추가 요청 기능명 Feature Name

Contibution 가이드 문서 작성

### 기능 상세 설명 Feature Description

Contribution Guide 를 아래와 같은 구성들처럼 확인할 수 있으면 좋겠습니다.

Contribution 을 좀 더 접근하기 쉽게 구성이 되면 좋겠습니다.
Readme.md 혹은 별도의 Contributing.md 등의 파일을 구성하여 Readme.md에 링크를 노출시키는 방법도 좋을 것 같습니다.
해당 구성으로 되어있는 Elastic Search Repository를 캡쳐로 첨부하였습니다.

![image](https://github.com/eGovFramework/egovframe-runtime/assets/38740832/3a2c14ef-ef14-4f9c-a185-ce624e743530)
![image](https://github.com/eGovFramework/egovframe-runtime/assets/38740832/ee857629-cc4b-4c45-afca-6f99c1d55205)

### 솔루션 관련 URL Solution-related URLs

https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md

**Comment by kim-hwi** [comment]
good idea!

**Comment by lat230627** [comment]
저도 같은 의견입니다. 가이드 문서를 md 파일이나 ascii-doc으로 관리했으면 좋겠습니다!

**Comment by eGovFrameSupport** [comment]
[2023 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'23년 4월 10일부터 8월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2023 전자정부 표준프레임워크 컨트리뷰션"을 실시 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.

https://forms.gle/g5cKfG5rnNrqvqjaA

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 감사장과 표준프레임워크 오픈커뮤니티에서 소정의 기념품을 택배 배송 해 드립니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by jei007** [comment]
표준프레임워크 발전을 위한 소중한 의견에 감사드립니다.
