### ISSUE TITLE
[기능요구(Feature)]: 빌드, 테스트,  CI등을 표시하는 다이어그램이 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by kim-hwi** [eGovFramework/egovframe-runtime#121]
### 연락처 Contact

whi78@naver.com

### 추가 요청 기능명 Feature Name

다이어그램 기능 추가

### 기능 상세 설명 Feature Description

현재 빌드는 어떻게 하고있는지, 어떤 이미지로 진행 하는지, 버전 별로 빌드에 사용되는 JDK는 무엇인지 등등을 한 눈에 볼 수 있는 
 다이어그램이 있었으면 좋겠습니다. (개발용, 배포용, 테스트 포함)
->
![image](https://github.com/eGovFramework/egovframe-runtime/assets/79562205/b5098c24-4434-4e4c-9dad-ef1b1c4df3aa)

추가적으로 해당 다이어그램을 readme.md에서 연결하여 볼 수 있는 뱃지가 있었으면 좋겠습니다.
-> 
![image](https://github.com/eGovFramework/egovframe-runtime/assets/79562205/e67a0894-e624-40eb-93ff-5f4acc50e0f7)

### 솔루션 관련 URL Solution-related URLs

https://ci.spring.io/teams/spring-boot/pipelines/spring-boot-3.2.x?group=system-tests

**Comment by eGovFrameSupport** [comment]
[2023 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'23년 4월 10일부터 8월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2023 전자정부 표준프레임워크 컨트리뷰션"을 실시 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.

https://forms.gle/g5cKfG5rnNrqvqjaA

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 감사장과 표준프레임워크 오픈커뮤니티에서 소정의 기념품을 택배 배송 해 드립니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by jei007** [comment]
표준프레임워크 발전을 위한 소중한 의견에 감사드립니다.
