### ISSUE TITLE
[기능요구(Feature)]: Issue 템플릿 추가 요청드립니다. 

### ISSUE THREAD

**Issue by lat230627** [eGovFramework/egovframe-runtime#122]
### 연락처 Contact

sleepred@gmail.com

### 추가 요청 기능명 Feature Name

Q&A Issue template 

### 기능 상세 설명 Feature Description

활셩화된 오픈소스 프로젝트는 Q&A Issue 템플릿으로 Q&A 관련 사이트(자체 Q/A사이트,  github discussion 등으로 간리하고 있습니다. 표준프레임워크는 자체 Q/A 사이트로 링크 걸면 될것 같습니다. 

(참고 ) 
vscode => github discussion 으로 관리 (https://github.com/microsoft/vscode-discussions/discussions)
![image](https://github.com/eGovFramework/egovframe-runtime/assets/137841878/b30201d1-d306-4a05-af4d-10b97c7c38f0)

### 솔루션 상세 Solution Details

Q/A issue template를 만들어서 표준프레임워크 사이트 묻고답하기(https://www.egovframe.go.kr/home/sub.do?menuNo=69)에 링크를 걸어 놓으면 사용자가 바로 Q/A 사이트를 확인 할 수 있어 편하게 Q/A 확인 및 등록을 할 수 있을 것 같습니다. 

(참고 ) 
vscode => github discussion 으로 관리 (https://github.com/microsoft/vscode-discussions/discussions)
![image](https://github.com/eGovFramework/egovframe-runtime/assets/137841878/b30201d1-d306-4a05-af4d-10b97c7c38f0)

### 솔루션 관련 URL Solution-related URLs

https://github.com/microsoft/vscode/issues/new/choose

**Comment by eGovFrameSupport** [comment]
[2023 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'23년 4월 10일부터 8월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2023 전자정부 표준프레임워크 컨트리뷰션"을 실시 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.

https://forms.gle/g5cKfG5rnNrqvqjaA

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 감사장과 표준프레임워크 오픈커뮤니티에서 소정의 기념품을 택배 배송 해 드립니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by jei007** [comment]
표준프레임워크 발전을 위한 소중한 의견에 감사드립니다.
