### ISSUE TITLE
[기능요구(Feature)]: 전자정부프레임워크를 사용하는 사람들간 정보를 공유하는 공간이 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by kim-hwi** [eGovFramework/egovframe-runtime#136]
### 연락처 Contact

whi78@naver.com

### 추가 요청 기능명 Feature Name

전자정부프레임워크 사용자간 정보공유공간 생성

### 기능 상세 설명 Feature Description

현재는 전자정부프레임워크를 사용하는 사용자들이 참여하여 정보를 서로 공유하고, 질문에 답변을 하는 공간(EX-단체채팅방)이 있으면 좋겠습니다. 
이 공간을 활용하여 사람들은 전자정부프레임워크에 대해 지식을 쌓고, 자주 발생하는 이슈들을 체크하여 전자정부프레임워크를 고도화 할 수 있다고 생각합니다.

### 솔루션 상세 Solution Details

SpringBoot에서는 Gitter라는 단체채팅방을 이용하여 사용자들간 질의응답을 하고있습니다.
![image](https://github.com/eGovFramework/egovframe-runtime/assets/79562205/9e7ca24f-d965-428e-bd52-93f9b2540ad7)
그리고 README.md에 뱃지를 통해 단체채팅방에 빠르게 입장할 수 있도록 하는 기능을 제공하고 있습니다.
![image](https://github.com/eGovFramework/egovframe-runtime/assets/79562205/97a1ff6c-13c9-49a3-9fa5-767504dbcbc8)

### 솔루션 관련 URL Solution-related URLs

https://app.gitter.im/#/room/#spring-projects_spring-boot:gitter.im

**Comment by jei007** [comment]
표준프레임워크 발전을 위한 소중한 의견에 감사드립니다.
