### ISSUE TITLE
[Bug]: EgovCommandLineRunner 클래스의 예외처리 수정 및 로그메세지 수정 필요

### ISSUE THREAD

**Issue by kim-hwi** [eGovFramework/egovframe-runtime#137]
### 연락처 Contact

whi78@naver.com

### 오류 내용 Error Description

Throwable에서 catch하던 NullPointerException를 분리하여 catch 할 필요성이 있어보입니다.
추가적으로 로그메세지에 오탈자가 있습니다.

### 오류 재현 방법 How to reproduce the error

해당 클래스의 start메서드 에서 익셉셥을 발생시킨다

### 환경정보 Environmental Information

 - OS정보 Operating System: 
 - 표준프레임워크 버전 eGovFrame Version: 4.0
 - JDK(JRE) 정보: 1.8
 - WAS 정보: 
 - DB 정보: 
 - 기타 환경 정보 Other environmental information:

**Comment by jei007** [comment]
표준프레임워크 발전을 위한 소중한 의견에 감사드립니다.
