### ISSUE TITLE
[Bug]: Changed Require Annotation, Deprecated

### ISSUE THREAD

**Issue by hckhead** [eGovFramework/egovframe-runtime#139]
### 연락처 Contact

yoo.insung@gmail.com

### 오류 내용 Error Description

Changed Require Annotation, Deprecated

명시적으로 @Autowired(Require=true) 로 변경필요 

### 오류 재현 방법 How to reproduce the error

(다음은 예시이며, 내용을 덮어 써 주세요. The following is an example, please overwrite the content.)

 1. 다음 메뉴를 선택한다. Select the following menu '...'
 2. 다음 버튼을 클릭한다. Click the Next button. '....'
 3. 다음 문구까지 스크롤 다운한다. Scroll down to the following phrase '....'
 4. 오류를 확인한다. Check for errors.

### 환경정보 Environmental Information

 - OS정보 Operating System: 
 - 표준프레임워크 버전 eGovFrame Version: 
 - JDK(JRE) 정보: 
 - WAS 정보: 
 - DB 정보: 
 - 기타 환경 정보 Other environmental information:

**Comment by hckhead** [comment]
Issue #132

**Comment by jei007** [comment]
표준프레임워크 발전을 위한 소중한 의견에 감사드립니다.
