### ISSUE TITLE
[기능요구(Feature)]: Log Util 기능 추가 건의

### ISSUE THREAD

**Issue by taehyun-learn** [eGovFramework/egovframe-runtime#140]
### 연락처 Contact

chris5207@naver.com

### 추가 요청 기능명 Feature Name

Log Util 기능 추가

### 기능 상세 설명 Feature Description

Log Util에 OFF, FINEST, INFO level에 대한 method만 있어
나머지 ALL, CONFIG, FINE, FINER, SEVERE, WARNING에 대한 기능 추가 건의 드립니다.

**Comment by jei007** [comment]
표준프레임워크 발전을 위한 소중한 의견에 감사드립니다.
