### ISSUE TITLE
[기능요구(Feature)]: Maven 빌드 CI/CD 구축

### ISSUE THREAD

**Issue by hckhead** [eGovFramework/egovframe-runtime#144]
### 추가 요청 기능명 Feature Name

CI/CD

### 기능 상세 설명 Feature Description

JDK 8 버전과, win, mac, linux 다양한 환경에서의 빌드 테스트 자동화

Create mavenBuild.yml for CICD

**Comment by hckhead** [comment]
PR  #127

**Comment by jei007** [comment]
표준프레임워크 발전을 위한 소중한 의견에 감사드립니다.
