### ISSUE TITLE
[Bug]: Make the enclosing method "static" or remove this set.

### ISSUE THREAD

**Issue by taehyun-learn** [eGovFramework/egovframe-runtime#145]
### 연락처 Contact

chris5207@naver.com

### 오류 내용 Error Description

다음은 sonarqube 스크린샷입니다.
![image](https://github.com/eGovFramework/egovframe-runtime/assets/19388823/2167749f-6392-42ea-a56b-d750b12c8092)

Make the enclosing method "static" or remove this set.
=> static 변수를 non-static method로 수정하고 있습니다.
=> static , static synchronized로 enclosing하거나 변수에서 static을 제거바랍니다.

### 오류 재현 방법 How to reproduce the error

(다음은 예시이며, 내용을 덮어 써 주세요. The following is an example, please overwrite the content.)

 1. 다음 메뉴를 선택한다. Select the following menu '...'
 2. 다음 버튼을 클릭한다. Click the Next button. '....'
 3. 다음 문구까지 스크롤 다운한다. Scroll down to the following phrase '....'
 4. 오류를 확인한다. Check for errors.

### 환경정보 Environmental Information

 - OS정보 Operating System: 
 - 표준프레임워크 버전 eGovFrame Version: 
 - JDK(JRE) 정보: 
 - WAS 정보: 
 - DB 정보: 
 - 기타 환경 정보 Other environmental information:

**Comment by jei007** [comment]
표준프레임워크 발전을 위한 소중한 의견에 감사드립니다.
