### ISSUE TITLE
[기능요구(Feature)]: math 관련 deprecated 문제해결

### ISSUE THREAD

**Issue by seungsupLee** [eGovFramework/egovframe-runtime#146]
### 연락처 Contact

uutmd91@gmail.com

### 추가 요청 기능명 Feature Name

math 관련 deprecated 문제해결

### 기능 상세 설명 Feature Description

math 관련 deprecated 문제해결

**Comment by seungsupLee** [comment]
#125

**Comment by jei007** [comment]
표준프레임워크 발전을 위한 소중한 의견에 감사드립니다.
