### ISSUE TITLE
[기능요구(Feature)]: replaceAll to replace 

### ISSUE THREAD

**Issue by seungsupLee** [eGovFramework/egovframe-runtime#147]
### 연락처 Contact

uutmd91@gmail.com

### 추가 요청 기능명 Feature Name

replaceAll to replace 

### 기능 상세 설명 Feature Description

replaceAll to replace

**Comment by seungsupLee** [comment]
#131

**Comment by jei007** [comment]
표준프레임워크 발전을 위한 소중한 의견에 감사드립니다.
