### ISSUE TITLE
[발전 방안 제안(Improvement Plan)]: 단위테스트, 통합테스트 시나리오 산출물 대체

### ISSUE THREAD

**Issue by Chung10Kr** [eGovFramework/egovframe-runtime#153]
### 아이디어명 Idea Name

단위테스트, 통합테스트 시나리오 산출물 대체

### 아이디어 요약 Idea Summary

표준프레임워크를 사용하여 진행하는 프로젝트에서, 표준프레임워크가 공인한 테스트 툴(예: Jacoco)를 사용하여 규칙에 맞게 작성된 테스트 코드를 작성하면, SI 프로젝트의 산출물인 단위테스트 및 통합테스트 시나리오를 대체할 수 있도록 제안합니다.

### 제안배경 Suggestion Background

현재 공공기관을 포함한 다양한 SI 프로젝트에서는 필수적으로 단위테스트 및 통합테스트 시나리오를 작성해야 합니다. 그러나 프로그램 개발 일정이 빠듯한 경우, 실제로 테스트를 수행하지 않고 형식적으로 산출물을 작성하는 경우가 발생할 수 있습니다. 또한, 테스트 코드가 작성되지 않으면, 추후 유지보수 과정에서 테스트 코드의 이점을 누릴 수 없습니다.

표준 프레임워크를 사용한 프로젝트에서, 표준 프레임워크가 공인한 테스트 툴 및 커버리지 툴을 사용하고, 표준 프레임워크의 테스트 규칙에 맞게 작성된 경우, 해당 툴에서 생성된 보고서를 SI 산출물인 단위테스트 및 통합테스트 시나리오의 대체 자료로 제안합니다. 이를 통해 실제 테스트 수행 여부를 확인하고, 프로젝트의 품질을 향상시킬 수 있습니다.

### 기대효과 Expectations

- 표준 프레임워크 활성화: 불필요한 산출물 제거와 테스트 규칙 제공을 통해 표준 프레임워크의 활성화를 촉진합니다.
- 형식적인 산출물 제거: 형식적인 산출물 대신, 실제 테스트 수행 결과를 확인할 수 있어, 문서의 신뢰성과 유용성을 높입니다.
- 테스트 코드 활성화: 산출물 작성을 위한 시간과 노력을 줄여, 테스트 코드 작성에 더 많은 시간을 할애할 수 있습니다.
- 유지보수의 효율성 증가: 테스트 코드를 통해 변경 사항에 대한 빠른 피드백을 제공하여, 유지보수 과정에서 발생할 수 있는 오류를 줄일 수 있습니다.
- 개발 표준화, 일관성 향상 : 표준 프레임워크가 공인된 테스트 규칙 사용을 권장함으로써, 개발 프로세스의 표준화와 일관성을 높일 수 있습니다.

### 자유기술 Free Writing

공공기관 SI 프로젝트에서 산출물의 기준을 변경하거나 법률적으로 개편하는 것은 쉽지 않을 수 있습니다. 하지만, 마치 명품 회사가 발행한 인증서가 제품의 정품 여부를 보장하는 것처럼, 표준프레임워크가 공인한 테스트 툴과 테스트 규칙을 준수한 산출물임을 인증하는 것만으로도 큰 도움이 될 것입니다. 이러한 방식은 형식적인 산출물 작성에서 벗어나 실제로 수행된 테스트의 신뢰성을 확보하는 데 기여할 수 있습니다. 이를 통해 개발자들은 실질적인 테스트 코드 작성에 집중할 수 있으며, 결과적으로 프로젝트의 품질과 유지보수 효율성을 높일 수 있습니다.

**Comment by jei007** [comment]
표준프레임워크에 대한 지속적인 참여 및 관심에 대하여
대단히 감사드립니다.
