### ISSUE TITLE
[발전 방안 제안(Improvement Plan)]: 디지털 정부서비스 UI/UX 가이드라인 추출

### ISSUE THREAD

**Issue by Samuel-Lee-kr** [eGovFramework/egovframe-runtime#159]
### 아이디어명 Idea Name

디지털 정부서비스 UI/UX 가이드라인 추출

### 아이디어 요약 Idea Summary

**디지털 정부서비스 UI/UX 가이드라인**의 샘플 프로젝트화

### 제안배경 Suggestion Background

- 시작 배경
  - 행정기관, 공공기관 등 다양한 곳에서 사용할 수 있도록 공개한 UI/UX가 존재함을 확인
  - 공개된 파일, 소스코드 등에 비해 접근성이 떨어지는 것을 확인(샘플 프로젝트가 존재하지 않음을 확인)

- 확인 내용
  - 표준프레임워크 오픈커뮤니티 자유게시판 문의 - NIA 기관에 직접 연락이 필요함을 확인 [관련 문의글](https://open.egovframe.org/oc/support/bbsItem.do?nttId=20905&pageIndex=2)
  - NIA에 문의 - KRDS 운영팀의 답변
    - 오픈소스로 제공되고 있으므로 별도의 라이선스 정책 없음
      (단, 민간 웹사이트의 경우 **컴포넌트>정부공식누리집 배너**를 사용할 수 없음)
    - 샘플 프로젝트(데모 프로젝트)는 제공하지 않음
    - 마크업 예시, CSS, JS, HTML 코드를 추출하여 활용할 것 허용

- 샘플 프로젝트 작성
  - HTML, CSS, JS 추출(sample 페이지, component 코드 분리)
  - CSS 수정(css 변수, 없는 이미지 참조 등) 
  - JS 수정(달력 UI 겹침 버그, 코치마크 Prev, Next 버튼 활성화 예시 코드, 텍스트 영역 최대숫자 연동 코드 등)
  - HTML 수정(컴포넌트 헤더 버그, 파일 업로드 UI 배치 등)

### 기대효과 Expectations

- 범정부 UI/UX 가이드라인 리소스를 확인 및 활용할 수 있는 기본 샘플 프로젝트(HTML, CSS, JS) 제공
- 추후 EgovFramework 기존 프로젝트에 소스 기여
  - React Project: [egovframe-template-simple-react](https://github.com/eGovFramework/egovframe-template-simple-react)
  - Spring Project: [egovframe-portal-site-template](https://github.com/eGovFramework/egovframe-portal-site-template)

### 자유기술 Free Writing

- [샘플 프로젝트 repository](https://github.com/Samuel-Lee-kr/krds_uiux)
- 샘플 프로젝트 작성과 관련하여 개발자 모임 진행 중 추후 React 프로젝트, JSP 프로젝트에 기여하기로 하였음

### 참고문헌 Reference

- [디지털 정부서비스 UI/UX 가이드라인](https://uiux.egovframe.go.kr/guide/index.html)
- [디지털 정부서비스 UI/UX 임시 웹사이트](https://uiux.egovframe.go.kr/pattern/worksheet.html)

**Comment by eGovFrameSupport** [comment]
안녕하세요
전자정부 표준프레임워크 센터입니다.

'24년 7월 29일부터 9월 30일까지 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2024년 전자정부 표준프레임워크 컨트리뷰션"을 개최 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며,  전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다. 
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.

앞으로도 전자정부 표준프레임워크에 지속적인 관심 바라오며, 아래 URL 접속, 설문지로 이동하여 항목에 응답 부탁드립니다.
https://forms.gle/6qRXGFZn5WTaxBCK8

※ 컨트리뷰션 종료 후, 시상관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by jei007** [comment]
표준프레임워크에 대한 지속적인 참여 및 관심에 대하여
대단히 감사드립니다.

**Comment by Samuel-Lee-kr** [comment]
KRDS 의 사용범위 재안내 메일을 받고 변경된 사항 코멘트 남겨 놓습니다.

2024. 8. 28.
KRDS 운영팀에서 
별도의 라이선스가 없고 샘플 프로젝트를 제공하지 않지만
공개된 가이드라인 구성요소의 마크업 예시,
서비스패턴의 HTML, CSS, JS 코드를 추출하여 활용해도 된다고 답변을 받았었습니다.

2024. 10. 18.
KRDS 운영팀에서 재안내 답변이 왔고
오픈소스로 공개되어 민간에서도 본 가이드라인을 활용하여 웹/앱을 구축할 수 있으나
본 가이드라인 기반의 디자인/개발 리소스에 대한 재가공/재배포 및 상업적 이용을 금지한다는
사용범위 메일이 왔습니다.

**'범정부 UI/UX 디자인 시스템 구축 및 가이드라인 고도화'** 과업을 통해
리소스 개발 및 디자인 시스템을 구축하고 공개하기 위해 저런 정책으로 변경한 것으로 보입니다.



관련되어 표준프레임워크 오픈커뮤니티 사무국에도 내용 전달해놓은 상태이며
샘플 프로젝트의 공개범위를 private으로 변경하였으니, 내용 참고하여 주시기 부탁드리겠습니다.

추후 과업을 통해 만들어진 산출물의 라이선스가 아무런 이슈가 없다고 한다면
다음에 있을 기회에 개선된 이슈 혹은 코드반영으로 기여할 수 있도록 하겠습니다.

긴 글 읽어주셔서 감사드립니다.
