### ISSUE TITLE
maven build 오류 

### ISSUE THREAD

**Issue by davidyu62** [eGovFramework/egovframe-runtime#38]
local 환경에서 maven install 시 dependency 오류 발생
error : Failure to find org.springmodules:spring-modules-validation:jar:0.9

해당 오류에 대한 설정 변경 혹은 guide가 필요

**Comment by Jadeu3** [comment]
Missing Artifact 발생하는 pom.xml 에 아래와 같이 전자정부프레임워크 Maven 리파지토리를 추가하면 해당 에러는 해결 됩니다.
# pom.xml
 (중략)
 <repositories>
		<repository>
			<id>egovframe</id>
			<url>http://www.egovframe.go.kr/maven/</url>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
<project> 

다만 빌드 수행 시 Test 에러가 많이 발생합니다. 좀 더 진행해 봐야겠습니다.

**Comment by jei007** [comment]
참여해 주셔서 감사합니다.
