### ISSUE TITLE
pom.xml 파일 구조 관리 개선 

### ISSUE THREAD

**Issue by seosej** [eGovFramework/egovframe-runtime#88]
- As-is
현재 하위 모듈 프로젝트 각각 pom.xml 파일이 존재하고 그 안에 \<properties\> 가 각각 설정되어 있습니다. 
그래서 properties 수정이 필요할 경우 모듈 프로젝트 별로 모든 pom.xml 파일의 \<properties\> 값을 일일히 수정해줘야 하는 번거로움이 있습니다. 

- 제안
가장 상위 pom.xml 파일에 \<properties\> 를 관리하고 
하위 모듈 프로젝트의 pom.xml 파일에서는 \<parent\> 로 상위 pom.xml 파일의 \<properties\> 값을 받아서 통합 관리 하면 추후 버전 관리 나 설정 값 관리에 용이할 것 같습니다. 

- 참고 예시
spring-batch (https://github.com/spring-projects/spring-batch) 의 경우 
가장 상위 pom.xml 파일(https://github.com/spring-projects/spring-batch/blob/main/pom.xml) 에 아래와 같이 \<properties\> 가 정의되어 있습니다. 
![image](https://user-images.githubusercontent.com/67827968/179464857-086af38d-aca2-4c78-add7-c2bea5b374e1.png)

그리고 하위 모듈 프로젝트의 pom.xml 파일(https://github.com/spring-projects/spring-batch/blob/main/spring-batch-core/pom.xml)을 보면 \<parent\>를 설정하여 상위 pom.xml 파일의 \<properties\> 값을 받아올 수 있습니다. 
![image](https://user-images.githubusercontent.com/67827968/179465591-87b94949-c056-4f96-903c-5e736bcffe6a.png)

**Comment by eGovFrameSupport** [comment]
[2022 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'22년 3월 28일부터 7월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2022 전자정부 표준프레임워크 컨트리뷰션"을 개최 하고 있습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL 또는 첨부의 QR코드 인식하셔서 설문지로 이동, 항목에 응답 부탁드립니다.
http://forms.gle/nWPW3cpnUs3Azjur5

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 컨트리뷰션 종료 후, 시상관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by jei007** [comment]
참여해 주셔서 감사합니다.
