### ISSUE TITLE
💡 README.md 작성이 필요할 것 같습니다

### ISSUE THREAD

**Issue by oleveloper** [eGovFramework/egovframe-runtime#89]
현재 프로젝트 README.md 에 Release note가 올라와 있습니다만, 더 많은 분들의 표준 프레임워크 개발 참여를 위해 README.md 에 다음과 같은 내용이 업데이트 되면 좋을 것 같습니다. 

- 프로젝트 목적
- 프로젝트 내용
- 동작 환경
- 빌드 방법
  - 빌드 방법 
  - 자주 사용되는 build options 
- Coding convention 
  - Coding convention 
  - Check style 적용 방법
- 라이선스
- 기여 방법
  - 기여 방법에 대한 자세한 설명을 담은 Link 

아래의 예시 Repository README.md를 참고하여 작성하면 더욱 좋을 것 같습니다.
- [Kafka](https://github.com/apache/kafka)
- [Spring](https://github.com/spring-projects/spring-framework)

**Comment by enlena612** [comment]
링크가 연결 안되는 것 같습니다 ~

**Comment by oleveloper** [comment]
> 

수정하였습니다. 감사합니다 !

**Comment by enlena612** [comment]
@oleveloper 연결 잘됩니다 ; )

**Comment by jei007** [comment]
참여해 주셔서 감사합니다.
