### ISSUE TITLE
Local maven 빌드가 실패합니다.

### ISSUE THREAD

**Issue by limeleaf** [eGovFramework/egovframe-runtime#90]
Local maven 빌드 수행시 다음과 같은 메시지가 출력되면서 빌드가 실패합니다.

오류 메시지
```
~~~ 중략 ~~~
[INFO] org.egovframe.rte.ptl.mvc .......................... FAILURE [  1.454 s]
[INFO] org.egovframe.rte.psl.data.jpa ..................... SKIPPED
[INFO] org.egovframe.rte.psl.data.mongodb ................. SKIPPED
[INFO] org.egovframe.rte.itl.integration .................. SKIPPED
[INFO] org.egovframe.rte.itl.webservice ................... SKIPPED
[INFO] org.egovframe.rte.bat.core ......................... SKIPPED
[INFO] org.egovframe.rte.root ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.195 s
[INFO] Finished at: 2022-07-18T17:20:40+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project org.egovframe.rte.ptl.mvc: Could not resolve dependencies for project org.egovframe.rte:org.egovframe.rte.ptl.mvc:jar:4.0.0: Failed to collect dependencies at org.egovframe.rte:spring-modules-validation:jar:0.9: Failed to read artifact descriptor for org.egovframe.rte:spring-modules-validation:jar:0.9: Could not transfer artifact org.egovframe.rte:spring-modules-validation:pom:0.9 from/to egovframe (https://maven.egovframe.go.kr/maven/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
```

히스토리를 확인해보니  [maven build 오류 이슈 링크](https://github.com/eGovFramework/egovframe-runtime/issues/38) 이슈와 유사한 상황으로 판단되지만, 다른 해결책으로 다음과 같이 최상위 pom.xml에 다음과 같이 spring-modules-validation 모듈이 먼저 빌드되도록 수정하면 빌드가 가능한 것으로 판단됩니다.

AS-IS
```
		<!-- Presentation -->
		<module>Presentation/org.egovframe.rte.ptl.mvc</module>
```

TO-BE
```
		<!-- Presentation -->
		<module>Presentation/spring-modules-validation</module>
		<module>Presentation/org.egovframe.rte.ptl.mvc</module>
```

**Comment by limeleaf** [comment]
https://www.egovframe.go.kr/home/ntt/nttRead.do?pagerOffset=0&searchKey=&searchValue=&menuNo=65&bbsId=4&nttId=1743 에서 다운받은 개발도구에 포함된 Repository에는 spring-modules-validation 라이브러리가 기본적으로 포함되어 있어서 빌드에 성공하지만, 해당 개발 도구를 사용하지 않는 경우에는 빌드에 실패합니다.

**Comment by eGovFrameSupport** [comment]
[2022 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'22년 3월 28일부터 7월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2022 전자정부 표준프레임워크 컨트리뷰션"을 개최 하고 있습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL 또는 첨부의 QR코드 인식하셔서 설문지로 이동, 항목에 응답 부탁드립니다.
http://forms.gle/nWPW3cpnUs3Azjur5

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 컨트리뷰션 종료 후, 시상관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by jei007** [comment]
참여해 주셔서 감사합니다.
