### ISSUE TITLE
JDK 11 환경에서 build 시 컴파일 오류 발생

### ISSUE THREAD

**Issue by gongpyung** [eGovFramework/egovframe-runtime#92]
JDK 11 환경에서 build 시 컴파일 오류 발생합니다. (JDK 8 버전에서는 build 성공했습니다.)
해당 화면 아래에 첨부합니다~

![image](https://user-images.githubusercontent.com/8156548/179472914-3c26e054-96da-432b-9bde-dea414e939be.png)
![image](https://user-images.githubusercontent.com/8156548/179473181-6041e45b-618b-4397-bafa-f6788def3c40.png)

**Comment by eGovFrameSupport** [comment]
[2022 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'22년 3월 28일부터 7월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2022 전자정부 표준프레임워크 컨트리뷰션"을 개최 하고 있습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL 또는 첨부의 QR코드 인식하셔서 설문지로 이동, 항목에 응답 부탁드립니다.
http://forms.gle/nWPW3cpnUs3Azjur5

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 컨트리뷰션 종료 후, 시상관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by feeva** [comment]
런타임 라이브러리는 사용자가 직접 컴파일해서 사용하는 용도가 아니라 바이너리 라이브러리를 가져다 사용하는 용도이므로 컴파일러 버전을 올리기 위해 마스터 소스를 고치기 보다는 사용하는 입장에서 각자 환경에 맞게 고쳐 사용하는 것이 맞다고 생각됩니다.

한편으로 등록자가 올리신 그림을 제가 들여다보니 toArray 메서드의 오버로딩 때문에 발생하는 문제입니다. `toArray((Object[])null)`로 수정하시면 해결하실 수 있습니다.

**Comment by jei007** [comment]
참여해 주셔서 감사합니다.
